import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './paths.mjs';
import { randomUUID } from 'node:crypto';
import { projectSchema, readiness, digest, publicProject, slug } from './project.mjs';
import { buildFiles } from './render.mjs';

export function ghPath(){const bundled=join(ROOT,'tools',process.platform==='win32'?'gh.exe':'gh');return process.env.PROTEST_GH_PATH || (existsSync(bundled)?bundled:'gh');}
export function gh(args,input,timeout=60000){return new Promise((resolve,reject)=>{const child=spawn(ghPath(),args,{windowsHide:true,stdio:['pipe','pipe','pipe'],env:{...process.env,GH_PROMPT_DISABLED:'1'}});let out='',err='',done=false;const timer=setTimeout(()=>{child.kill();reject(new Error('GitHub took too long. Check your connection and try again.'));},timeout);child.on('error',()=>{clearTimeout(timer);reject(new Error('GitHub CLI is missing. Use the complete Protest download, which includes it, or install GitHub CLI.'));});child.stdout.on('data',d=>{out+=d;if(out.length>12_000_000)child.kill();});child.stderr.on('data',d=>{err+=d;});child.on('close',code=>{if(done)return;done=true;clearTimeout(timer);if(code===0)resolve(out);else{const e=new Error(err.includes('404')?'GitHub resource not found.':err.includes('401')||err.includes('auth login')?'Sign into GitHub to continue.':err.includes('403')?'GitHub denied this action. Check your account permissions and Pages availability.':err.includes('422')?'GitHub rejected the request. The repository name may already be taken or Pages may already be configured.':'GitHub request failed. Check your connection, sign in, and try again.');e.status=Number(err.match(/HTTP (\d{3})/)?.[1]||0);reject(e);}});child.stdin.end(input);});}
export async function api(endpoint,method='GET',body){const raw=await gh(['api',endpoint,'--method',method,'-H','Accept: application/vnd.github+json',...(body!==undefined?['--input','-']:[])],body!==undefined?JSON.stringify(body):undefined);return raw.trim()?JSON.parse(raw):null;}
export class GitHubPublisher {
  constructor(store,client=api){this.store=store;this.api=client;this.plans=new Map();this.busy=false;this.login={state:'idle'};}
  async account(){try {const user=await this.api('user');return {connected:true,login:user.login};}catch(e){return {connected:false,message:e.message};}}
  startLogin(){if(this.login.state==='pending')return this.login;this.login={state:'pending',message:'Opening GitHub sign in. Follow the browser instructions.'};const child=spawn(ghPath(),['auth','login','--hostname','github.com','--git-protocol','https','--web'],{windowsHide:true,stdio:['pipe','pipe','pipe']});const receive=d=>{const s=d.toString(),match=s.match(/\b[A-Z0-9]{4}-[A-Z0-9]{4}\b/);if(match)this.login={state:'pending',code:match[0],url:'https://github.com/login/device',message:'Enter this one time code on GitHub. Your credentials stay with GitHub CLI.'};};child.stdout.on('data',receive);child.stderr.on('data',receive);child.on('error',()=>{this.login={state:'error',message:'GitHub CLI is missing. Install the complete Protest download.'};});child.on('close',code=>{this.login={state:code===0?'complete':'error',message:code===0?'Signed in. You can prepare your publication.':'Sign in did not finish. Try again.'};});child.stdin.end();setTimeout(()=>{if(this.login.state==='pending'){child.kill();this.login={state:'error',message:'Sign in expired. Try again.'};}},15*60*1000).unref();return this.login;}
  async destination(p){const user=await this.api('user'),repo=p.repo||slug(p.title); if(!/^[a-z0-9][a-z0-9-]{0,69}$/.test(repo))throw new Error('Invalid repository name.');const full=`${user.login}/${repo}`,url=`https://${user.login.toLowerCase()}.github.io/${repo}/`;let info=null,head=null;try{info=await this.api(`repos/${full}`);}catch(e){if(e.status!==404)throw e;}if(info){if(info.private)throw new Error('Choose a new repository name. Protest publishes only into its own public event repositories.');let marker;try{const f=await this.api(`repos/${full}/contents/protest-public.json`);marker=JSON.parse(Buffer.from(f.content,'base64').toString());}catch{}const previous=await this.store.read('deployment.json',null);if(marker?.id!==p.id && !(previous?.projectId===p.id&&previous?.repository===full&&previous?.createdRepository))throw new Error('That repository belongs to another project. Choose a new repository name.');head=(await this.api(`repos/${full}/git/ref/heads/${info.default_branch}`)).object.sha;await this.checkPages(full,info.default_branch);}
    return {repository:full,repo,owner:user.login,url,exists:!!info,branch:info?.default_branch||'main',head};}
  async checkPages(repository,branch){let pages;try{pages=await this.api(`repos/${repository}/pages`);}catch(e){if(e.status!==404)throw e;}if(pages&&(pages.cname||pages.source?.branch!==branch||pages.source?.path!=='/'))throw new Error('This repository has different Pages settings. Review them on GitHub before publishing again.');return pages;}
  async prepare(project){const p=projectSchema.parse(project),issues=readiness(p);if(issues.length)throw new Error(issues.join(' '));const dest=await this.destination(p),built=await buildFiles(p,dest.url),planId=randomUUID();const plan={planId,projectId:p.id,projectHash:digest(p),project:p,revision:built.revision,files:built.files,...dest,expires:Date.now()+10*60*1000};this.plans.clear();this.plans.set(planId,plan);return {planId,repository:dest.repository,url:dest.url,exists:dest.exists,revision:built.revision,files:Object.entries(built.files).map(([name,data])=>({name,bytes:data.length})),publicDetails:publicProject(p),example:p.example};}
  async publish(planId,project){if(this.busy)throw new Error('A publication is already in progress.');const plan=this.plans.get(planId);if(!plan||plan.expires<Date.now())throw new Error('This preview expired. Prepare a fresh publication.');if(plan.projectHash!==digest(projectSchema.parse(project)))throw new Error('The project changed. Review a fresh publication before publishing.');this.busy=true;let deployment={projectId:plan.projectId,repository:plan.repository,url:plan.url,revision:plan.revision,state:'publishing',startedAt:Date.now(),message:'Preparing your repository.',createdRepository:!plan.exists};try{
      const user=await this.api('user');if(user.login!==plan.owner)throw new Error('The signed in account changed. Prepare a fresh publication.');
      let branch=plan.branch,head=plan.head;
      if(!plan.exists){const info=await this.api('user/repos','POST',{name:plan.repo,description:'Event information published with Protest.',private:false,auto_init:true});branch=info.default_branch;await this.store.write('deployment.json',deployment);head=(await this.api(`repos/${plan.repository}/git/ref/heads/${branch}`)).object.sha;}
      else {await this.checkPages(plan.repository,branch);const current=(await this.api(`repos/${plan.repository}/git/ref/heads/${branch}`)).object.sha;if(current!==head)throw new Error('The repository changed since your preview. Prepare it again to preserve those changes.');}
      const base=await this.api(`repos/${plan.repository}/git/commits/${head}`),tree=[];
      deployment.message='Uploading the reviewed site and fliers.';await this.store.write('deployment.json',deployment);
      for(const [path,data] of Object.entries(plan.files)){const blob=await this.api(`repos/${plan.repository}/git/blobs`,'POST',{content:data.toString('base64'),encoding:'base64'});tree.push({path,mode:'100644',type:'blob',sha:blob.sha});}
      const newTree=await this.api(`repos/${plan.repository}/git/trees`,'POST',{base_tree:base.tree.sha,tree});const commit=await this.api(`repos/${plan.repository}/git/commits`,'POST',{message:`Publish Protest: ${plan.project.title}`,tree:newTree.sha,parents:[head]});
      await this.api(`repos/${plan.repository}/git/refs/heads/${branch}`,'PATCH',{sha:commit.sha,force:false});deployment.commit=commit.sha;
      let pages;try{pages=await this.api(`repos/${plan.repository}/pages`);}catch(e){if(e.status!==404)throw e;}
      if(!pages)await this.api(`repos/${plan.repository}/pages`,'POST',{build_type:'legacy',source:{branch,path:'/'}});
      else if(pages.cname || pages.source?.branch!==branch || pages.source?.path!=='/')throw new Error('This repository has different Pages settings. Review them on GitHub before publishing again.');
      deployment={...deployment,state:'building',message:'GitHub is building your site. Keep this window open to verify it.'};await this.store.write('deployment.json',deployment);this.plans.delete(planId);return deployment;
    }catch(e){deployment={...deployment,state:'error',message:e.message};await this.store.write('deployment.json',deployment);throw e;}finally{this.busy=false;}}
  async status(project){const d=await this.store.read('deployment.json',null);if(!d||d.projectId!==project.id)return null;if(d.state==='publishing'||d.state==='building'||d.state==='live'){
      try{const u=new URL(d.url);if(u.protocol!=='https:'||!u.hostname.endsWith('.github.io')||u.username||u.password)throw new Error('Unexpected site address.');const response=await fetch(`${d.url}?protest_revision=${d.revision}`,{signal:AbortSignal.timeout(12000),redirect:'error'});const html=await response.text();if(response.ok&&html.includes(`name="protest-revision" content="${d.revision}"`)){d.state='live';d.message='Verified: the live page matches your published version.';d.verifiedAt=new Date().toISOString();await this.store.write('deployment.json',d);}else if(d.state==='live'){d.state='building';d.message='The expected version is not currently available. Check again shortly.';}}
      catch{if(d.state==='live'){d.state='building';d.message='Could not verify the live page. Check your connection and try again.';}}
    }if(['publishing','building'].includes(d.state)&&d.startedAt&&Date.now()-d.startedAt>15*60*1000){d.state='error';d.message='The published version was not verified within 15 minutes. Check this repository’s Pages settings and Actions on GitHub, then review a fresh publication to retry.';await this.store.write('deployment.json',d);}return {...d,hasUnpublishedChanges:d.revision!==digest(publicProject(project))};}
}
